Fix data-bs-parent
Currently, we get a JS error (Uncaught TypeError: 'querySelectorAll' called on an object that does not implement interface Element.)

This, as is, fixes the expected default behavior (see https://getbootstrap.com/docs/5.0/components/accordion/#example).
If implemented the right kwarg in Container class on bootstrap.py, this will also allow for the always open behavior (see https://getbootstrap.com/docs/5.0/components/accordion/#always-open), since all we need is get rid of data-bs-parent.